### PR TITLE
Creating TXT file automatically while creating the PR

### PR DESCRIPTION
**Pull request by BassCoder2808**
- Address Issue #399 
- Added the functionality of creating the Txt file in the PR
- Added a new field in the model to store the License Text

### CODE REVIEW

**Comment by BassCoder2808** [comment]
Hi @goneall tagging you here for the issue #399 , let me know if anything else needs to be changed in this, just fixed the migration file which was causing the problem before

**Comment by goneall** [comment]
@BassCoder2808 - I just tried this on my local machine, and I didn't have the same error on the upgrade, but I ran into a database error when I tested out the license submit.  Below is the error:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute return Database.Cursor.execute(self, query, params) sqlite3.IntegrityError: NOT NULL constraint failed: app_licenserequest.text The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/spdxonlinetools/src/app/views.py", line 162, in submitNewLicense licenseRequest.save() File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save self.save_base(using=using, force_insert=force_insert, File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base updated = self._save_table( File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw) File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert return manager._insert( File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert return query.get_compiler(using=using).execute_sql(returning_fields) File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute return super().execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute with self.db.wrap_database_errors: File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute return Database.Cursor.execute(self, query, params) django.db.utils.IntegrityError: NOT NULL constraint failed: app_licenserequest.text
Submit a New License to the SPDX License List

Please review the [SPDX License List inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) before submitting a new license. Once you have submitted a license, please follow the [issue in Github](https://github.com/spdx/license-list-XML/issues) and be prepared to help create the required XML and test text files if the license is accepted for submission.
Briefly explain how this license
meets the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md)
test
Full name or title of license
Test license - please ignore
Suggest short identifier
(See [Fields, section B](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md) for more details)
test-license
URL to license text
http://example.com
+ Add a source
OSI Status
Submitted, but pending
Text of license
test
License author or steward?
(If not known, put 'Unknown')
Unknown
URL to project(s) that use license
http://example1.com
+ Add an example project URL
```

**Comment by goneall** [comment]
If you want to try to reproduce the issue, attached is the SQLite file from before the upgrade:

[db.zip](https://github.com/spdx/spdx-online-tools/files/11960846/db.zip)


I just ran the docker build and tested out the submit.

**Comment by BassCoder2808** [comment]
Hi @goneall I tried with the `db.sqlite` file which you had provided, but I am not facing the error on my local machine.
image
I submitted the new license and it did not throw the error.
I ran the commands `makemigations` and `migrate` after changing the db file and after that error was gone.
Can you please check again like going into the `django admin` dashboard like were the chages made,because the error mentions the `text_field` and I have provided the `default value=""` so that shouldn't voilate any previous constraints, so I think the migrations might have not been properlyapplied.
Let me know if anything else needs to be done or some other error arises

**Comment by goneall** [comment]
@BassCoder2808 To reproduce the error - start with the code in the main branch before updating the code with the PR.  Then update the code - the database should upgrade without error.  When using the Docker image, it failed.  Let me know if you followed the same steps.

**Review by goneall — APPROVED** [review]
LGTM - Reviewed online - passing tests

**Pull request merged**
