### PR TITLE
Merge python3 to master

### PR DESCRIPTION
**Pull request by rtgdk**

### CODE REVIEW

**Comment by goneall** [comment]
@rtgdk I just pulled the latest python3 branch and ran the unit tests.  It generated the following error below.  If I have some time later today, I'll look into the cause a bit more.

```
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 421, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "api_submitlicensemodel" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\commands\test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\test\runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\test\runner.py", line 643, in setup_databases
    return _setup_databases(
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\test\utils.py", line 179, in setup_databases
    connection.creation.create_test_db(
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\base\creation.py", line 74, in create_test_db
    call_command(
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\operations\models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\base\schema.py", line 331, in create_model
    self.execute(sql, params or None)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\base\schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 421, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "api_submitlicensemodel" already exists
```

**Comment by rtgdk** [comment]
@goneall This looks like a migration issue. The table `api_submitlicensemodel` already exists in your local database. To tun the test successful delete existing SQL database locally and then run `python manage.py migrate`

I will have to check how to migrate successfully once we upgrade django and python their. Will check how django manages migrations across versions else we will have to restore the data from postgres backup like we did last time.

**Comment by goneall** [comment]
@rtgdk I deleted the database and reran the tests - the same error occurred.

I'll investigate a bit and see if I can narrow down the cause.

**Comment by goneall** [comment]
Deleting the file `src/api/migrations/0002_submitlicensemodel.py` solve the issue.

I created PR #348 to remove the file.

I'm not sure if this causes any other side-effects - @rtgdk if you could review and merge if OK.

Other than that, the merge looks good.

**Comment by goneall** [comment]
Thanks @rtgdk - that was a big task getting things up to Python3.

**Pull request merged**
