### PR TITLE
Change the comments field to report the comments in the issues

### LINKED ISSUE #98: Change the comments field to report the comments in the issues and not include in notes
Currently, when you submit a license, the comments are included in the notes section of the XML.

The legal team would like to include the comments in the Issues submitted to the license-list-XML repo and not include it in the `<notes> ... </notes>` section of the XML.  We'll reserve the notes section of the XML for legal team use.

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #98

### CODE REVIEW

**Comment by Ugtan** [comment]
@goneall For now i have kept the `licenseNotes` field in the views to be a empty string as i don't know how the legal team would like to use that field and also, i will wait for your reply for any further changes.

After submitting the license the issue looks like [this](https://github.com/spdx/TEST-LicenseList-XML/issues/8). From the license i submitted i found out that there are no validations checks to check if the user enter a valid url. We should ensure that it is a url and not a regular string right?

**Comment by goneall** [comment]
> We should ensure that it is a url and not a regular string right?

I think that would be a good idea.  If you don't mind adding that to this PR, I can merge that in as well.

**Comment by Ugtan** [comment]
@goneall Sure. I will add that as well.

**Comment by goneall** [comment]
@jlovejoy For the notes and comments, we are using comments as text the license submitter adds when submitting a license.  The comments just go into the github issue and not the XML.

Do you see any need for the license submitter to be allowed to also add notes for the license or is that something that only the legal team should manage?  IMHO, we should only allow the comments and not confuse the user with notes in the license submittal form.

**Comment by Ugtan** [comment]
@goneall Done. Please have a look at it.

**Comment by goneall** [comment]
@Ugtan @jlovejoy Talked to Paul today from the legal team and we both though there is no need to include the license-XML notes in the form.

@Ugtan Let's go ahead and remove the licenseNotes field from the code just to clean it up a bit.  After that, I'll merge and deploy.

**Comment by Ugtan** [comment]
> @Ugtan Let's go ahead and remove the licenseNotes field from the code just to clean it up a bit. After that, I'll merge and deploy.
I agreed with you on not including the notes via forms. But, removing the `licenseNotes` will remove the field notes from the license xml. So, you want to remove them from the license that are submitted as well? @goneall

**Comment by goneall** [comment]
@Ugtan the `<notes>` element is optional in the XML, so we could remove it.   After going back and looking at the code again I'm now thinking it is only a couple lines of code we would be cleaning up.  Leaving it would keep a hook in case we want to add notes in the future.  Let's leave it as is.  I'll merge and deploy.

Thanks for the contribution!

**Comment by Ugtan** [comment]
Okay. I just wanted to make sure that it should be removed from the license xml as well.

And I'm glad i could contribute 😊

**Pull request merged**
