### PR TITLE
Fix button in error templates

### PR DESCRIPTION
**Pull request by Ugtan**
The home page button in error templates was not working, now it takes the user to the
home page after clicking on it.

### CODE REVIEW

**Comment by rtgdk** [comment]
@Ugtan Are you sure about this? It should work fine since we are extended base html and loading all static files. If not, can you please specify which url was the button taking you to previously?

**Comment by Ugtan** [comment]
You are right it should work but it was not working in mine as i am using firefox browser. After a quick search i found out that it doesn't work in firefox, you can refer [here](https://stackoverflow.com/questions/16280684/nesting-a-inside-button-doesnt-work-in-firefox). So i tried to fix it using js onclick. Another possible solution would be `<a href="#"><button class="btn"></button></a>` as mentioned in the above link.

**Comment by rtgdk** [comment]
@Ugtan Okay, I was testing on Chrome. Using `<a> tag` with `class="btn btn-lg btn-info"` would be good.
Update it and I'll merge the PR.

**Comment by Ugtan** [comment]
@rtgdk okay will do it soon.

**Comment by Ugtan** [comment]
@rtgdk Done. Please have a look.

**Pull request merged**
