### PR TITLE
Rename 'XML Editor' to 'License XML Editor'

### LINKED ISSUE #40: Rename “XML Editor” to “License XML Editor” to clarify its intended use (was: Add support for other valid extensions)
<del>

Currently it seems the upload (to XML Editor at least) only accepts files with an `*.xml` extension.

According to §1.6.9 of the [SPDX Specification 2.1][spec] it 
> [s]hould be easy to recognize in a file system without opening the file.  A suggested naming convention is to use *.spdx (for tag-value format) and *-spdx.rdf for RDF format.

So while `*.spdx` for tag-value and `*-spdx.rdf` are not a required naming, they are conventions that the SPDX Online Tools should at least support.

</del>

<ins>

As explained by @goneall in the first comment below, the underlying issue seems to stem from the ambiguous name of the tool. A simple renaming should be enough.

</ins>
[spec]: https://spdx.org/spdx-specification-21-web-version#h.3dy6vkm

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #40

### CODE REVIEW

**Comment by rtgdk** [comment]
If we are changing to `License XML Editor`, it would make sense to change the url and views function name and documentation too.

**Comment by Ugtan** [comment]
Definately. I will do it shortly.

**Comment by Ugtan** [comment]
@rtgdk I have updated the requested changes and also rebased the branch. Please have a look when you are free. Thanks :)

**Comment by goneall** [comment]
@Ugtan The changes look good to me - If you could rebase and resolve the merge conflicts, I'll merge it in and deploy

**Comment by Ugtan** [comment]
@goneall Done. Please have a look.

**Comment by goneall** [comment]
This is now deployed on SPDX tools.  @Ugtan Thanks for the contribution!

**Comment by Ugtan** [comment]
Thank you 😊 @goneall looks good. Thanks for the update :)

**Pull request merged**
