### PR TITLE
Add instructions for updating the production database

### PR DESCRIPTION
**Pull request by goneall**
Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
@kmehant @Ugtan - Let me know if this is the correct method for updating the database or if we should somehow include it in the Docker file creation

**Review by Ugtan — COMMENTED** [review]
@goneall I guess this would work well with initialising or updating of the database. But, have you tried `docker-compose exec spdx_prod python manage.py migrate`?

**Comment by goneall** [comment]
@Ugtan Thanks for the suggestion - The only problem I can think of is we may need to stop the running instance first.

I haven't tried using docker-compose rather than docker.

**Comment by goneall** [comment]
I updated the instructions to use individual docker exec commands which is a bit easier than starting up the shell.

**Pull request merged**
