### PR TITLE
Add validations for license submittal fields

### LINKED ISSUE #115: Validate license submittal fields
This license name and license ID can be validated using the rules documented in the pop over text.  We can pick a max. length of a short identifier - perhaps 25 characters.  We can make sure all characters are valid.

For the license name, we can check for starting with "the", parenthesis, etc.

Check the pop over text for what can be validated.

This is related to issue #106

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #115

### CODE REVIEW

**Comment by Ugtan** [comment]
I have added the following validation checks for the listed license submittal fields:
1. **License Fullname**
The validation checks added for the license fullname are-
[x] Restrict words starting with *the* for alphabetical sorting purposes.
[x] No commas in the license fullname or exception.
[x] Word *version* shouldn't be spelled out instead use 'v'.
[x] No period or space between version 'v' and version number.

2. **Short Identifier**
[x] Short identifiers must consists of ASCII letters (A-Za-z), digits (0-9), full stops (.) and hyphen or minus signs (-) only
P.s Short identifier cannot be more than 25 characters so, i don't think there is any need to validate it.

Please have a look and let me know if  i left some checks that needs to be covered. @goneall @techytushar

**Comment by Ugtan** [comment]
> you could add text to describe what the valid text would be.

Did you mean to add more description of the error or just give example of what valid field would look like? I am not able to understand, can you be more descriptive?

**Comment by goneall** [comment]
> Did you mean to add more description of the error or just give example of what valid field would look like? I am not able to understand, can you be more descriptive?

An ideal solution would be something very specific like "an invalid character '%' was found in the license ID".  Also, a very acceptable solution would be just to describe what is expected like "The license ID is invalid, short identifiers consist of ASCII letters ..."

I'll leave it to you how specific since there is a bit more work involved in giving the detailed descriptions.

**Comment by Ugtan** [comment]
> An ideal solution would be something very specific like "an invalid character '%' was found in the license ID". Also, a very acceptable solution would be just to describe what is expected like "The license ID is invalid, short identifiers consist of ASCII letters ..."

Okay, got it.


> I'll leave it to you how specific since there is a bit more work involved in giving the detailed descriptions.

Yeah, I will figure something out.

**Comment by Ugtan** [comment]
@goneall I have added a patch considering your feedback, please have a look. Thank you

**Comment by goneall** [comment]
@Ugtan Changes look good.

I'll go ahead and merge.

**Pull request merged**
