### PR TITLE
Resolve issue #252 - add text to top of license submittal page

### PR DESCRIPTION
**Pull request by goneall**
Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
Untitled

**Comment by goneall** [comment]
@swinslow @jlovejoy Please take a quick look at the attached image/PR and let me know if this resolves issue #252.

**Comment by swinslow** [comment]
@goneall This looks great to me!

**Review by swinslow — APPROVED** [review]

**Review by rtgdk — APPROVED** [review]
LGTM

**Pull request merged**
