### PR TITLE
Display of license header in github issue

### LINKED ISSUE #105: license submit: display of input in Github issue
If a field is left empty in the submission form, could we still have the heading for the field (e.g., "Standard License Header") appear in the auto-generated issue so we know more easily that was left blank?

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #105 
Tested and working [here](https://github.com/spdx/TEST-LicenseList-XML/issues/12).

### CODE REVIEW

**Comment by Ugtan** [comment]
Please have a look at it. @goneall @jlovejoy

**Comment by jlovejoy** [comment]
not sure how I look at it - if it's merged should I be seeing it in the tool?

**Comment by goneall** [comment]
@jlovejoy You won't see it in the tool until I deploy it.  If you click on the files changed tab, you'll see the code changes - but that only helps if you're a Python programmer ;)

I've reviewed the code and I think it is what you're looking for - so I'll go ahead and merge it.  I'll probably deploy it over the weekend.

**Comment by goneall** [comment]
@jlovejoy Oops - it is already merged - so I'll deploy this along with any other fixes over the weekend.

**Pull request merged**
