### PR TITLE
Add secret.py file and fix travis build error

### LINKED ISSUE #72: New travis script failing due to missing secret file
The following error is being reported by the Travis script:

```
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/python/2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/build/spdx/spdx-online-tools/src/src/settings.py", line 14, in <module>
    from secret import getGithubKey, getGithubSecret, getSecretKey
ImportError: No module named secret
```

This is due to the file containing the github secret info being missing.  I don't believe the current unit tests use the secrets, so may be able to get away with creating a set of fake credentials in a src/src/secret.py file to get around this issue.  Another approach would be to use encrypted environment variables to store the credentials in travis then create the secret.py file as part of the travis script.

### LINKED ISSUE #83: Travis build fails with 'geckodriver' executable needs to be in PATH error
Travis build fails with the `WebDriverException: Message: 'geckodriver' executable needs to be in PATH` error due to firstly, geckodriver not being installed and secondly, geckodriver executable needs to be in PATH variable.
travisbuild

### PR DESCRIPTION
**Pull request by Ugtan**
Add secret.py file for storing github API credentials as well as fix the travis build error of 'geckodriver' needs to be in PATH error

Fixes #72 
Fixes #83

### CODE REVIEW

**Comment by Ugtan** [comment]
@goneall I don't think so it will create a problem since the will be always ignored unless someone tries to forcibly pushes it or someone edits the .gitignore file. In that case, i think it will be better to use environment variables instead of using a fake credentials file like secret.py. lemme know what do you think.

**Comment by rtgdk** [comment]
@Ugtan Can you explain the changes related to `travis.yml`? I cannot understand the requirement of addons for firefox and headless argument. Also if you added these changes to fix any other issue other than `secret.py file issue`, please open that issue and reference this PR.

**Comment by Ugtan** [comment]
After adding the secret.py file, the travis was showing `WebDriverException: Message: 'geckodriver'
executable needs to be in PATH error` so i added a before script in travis to install geckodriver and add it to PATH variable. The selenium based tests required firefox, so i used addon for firefox to install a version which is compatible with geckodriver. The headless mode is just to run firefox without any visible UI components visible. @rtgdk

**Comment by goneall** [comment]
> @goneall I don't think so it will create a problem since the file will be always ignored unless someone tries to forcibly pushes it or someone edits the .gitignore file. In that case, i think it will be better to use environment variables instead of using a fake credentials file like secret.py. lemme know what do you think.

@Ugtan You solution of adding the file should work.

I'll go ahead and merge the PR.

Thanks for the contribution!

**Comment by Ugtan** [comment]
Thank you 😊 @goneall @techytushar @rtgdk

**Pull request merged**
