### PR TITLE
Update references to main

### PR DESCRIPTION
**Pull request by jlovejoy**
change master to main references to license list repo

@goneall - please check if this looks right!

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by goneall** [comment]
@jlovejoy Thanks for the PR

In looking at the code - it looks like the same code is used for updates to the namespace repo.

Rather than fix this in the code, I think I'll rename the master branch to main in the namespace repo.  @jlovejoy @swinslow Let me know if you have any concerns with this approach.

**Comment by jlovejoy** [comment]
sounds fine to me, @goneall 

is that why this PR is failing?

**Comment by goneall** [comment]
> is that why this PR is failing?

No - there are some known issues with the unit tests when running under the CI.  I end up having to look at each test result to see if a new error is introduced - rather inconvenient.  I noted the above just by reviewing the code.

**Comment by goneall** [comment]
I found 3 repos where we need to rename the default branch to match the license-list-XML repo.  I created issues for each of these to track - I'll wait a week or so just to make sure no one has any issues with the renaming - then I'll fix:

- https://github.com/spdx/license-namespace-test/issues/9
- https://github.com/spdx/TEST-LicenseList-XML/issues/122
- https://github.com/spdx/license-namespace/issues/5

**Comment by swinslow** [comment]
@goneall No concerns from me with the branch renaming, sounds good.

**Comment by rtgdk** [comment]
@goneall If we are on track for renaming `master` to `main`, we should also consider https://github.com/spdx/spdx-online-tools 😛 . Opened an issue for future #401

**Comment by goneall** [comment]
I've renamed the default branches for all the repos referenced in the online tools.

@jlovejoy - could you change the other references to `master` to refer to `main`?

Once that's done, I can give it a test and see if it solves the issue.

**Comment by goneall** [comment]
> If we are on track for renaming master to main, we should also consider https://github.com/spdx/spdx-online-tools 😛 . Opened an issue for future https://github.com/spdx/spdx-online-tools/issues/401

@rtgdk Good point - I should do the same for the Java repos.

**Comment by jlovejoy** [comment]
@goneall - updated 3 more references, I think that's all of them now. This included a link to the license-list-data repo as well.

**Comment by goneall** [comment]
@jlovejoy I rebased this PR with the fix for the docker problem - you should be able to just pull down the latest and test it out.

**Pull request merged**
