### PR TITLE
Add instructions for form fields in license submit

### LINKED ISSUE #106: license submit: instructions for fields/form
is it possible to add some instructions at the top of the page?

similarly, could we add hints for how to fill out some of the fields - maybe via a popup or via some text in the field that disappears when you then start typing?

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #106

### CODE REVIEW

**Comment by rtgdk** [comment]
The popover just flicker on small screen. Try to reduce your browser's screen and hover over the icon. (it might just be my browser, not sure) I am also not sure if it works correctly on mobile.

Still using bootstrap model is much better than simple hover. But I am not sure if this much text should be shown in hover. I think it should be condensed and link to https://spdx.org/spdx-license-list/license-list-overview#fields should be provided for further reference.

**Comment by goneall** [comment]
@rtgdk Thanks for checking that.

I just emulated a phone using Chrome and the popover text doesn't show up when the screen is too small.  It looks like we need to go with reduced text and a link to make this work on a mobile phone.

I think most people will be using a desktop, but we should make it work for phone as well.

**Comment by Ugtan** [comment]
@rtgdk @goneall I have adding a patch for the popover considering your feedback for making it more mobile friendly. The patch seems to work fine. Although, still some of the text may not be shown for the `shortIdentifier` as it is too long and will be exceeding the screen size and user has to scroll a bit to be able to see whole info. I will try to fix this, other than that i think it works well for the phones as well.

**Comment by Ugtan** [comment]
> I just emulated a phone using Chrome and the popover text doesn't show up when the screen is too small

That is probably due to the fact that hover doesn't exist for touch screen devices(except iphone). But i have fixed it and the popover is triggered on click in case of mobile phones and on hover in case of desktops. I have also tested it(on firefox) and it is working. But it doesn't show up as it should on mobile but its not too bad as well. I feel like a bit less text would make it better(if possible).

**Comment by goneall** [comment]
@Ugtan I just check the latest with your patch and the mobile works fine now.

**Comment by rtgdk** [comment]
LGTM. Still not too sure about the length of the hover text or if we should add a link to https://spdx.org/spdx-license-list/license-list-overview#fields . @goneall @techytushar  If it looks good to you, go ahead and merge.

**Comment by goneall** [comment]
I'll go ahead and merge and deploy so that @jlovejoy can review.

**Pull request merged**
