### PR TITLE
Add archive license request feature

### LINKED ISSUE #81: Add archive new license request
Currently, all license requests are displayed after being submitted.  At some point, the number of license requests may become overwhelming.  

Suggest adding an archive feature where you can archive an existing license request.  This could be a button on the submitted license list page that would be enabled when a license request is highlighted. It would be moved to an archive category which can have its own display.  In the archive display, the license request could be "unarchived" with an unarchive button.

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #81

### CODE REVIEW

**Comment by Ugtan** [comment]
P.S it is not completed i still have to write tests for the same as well.

**Comment by Ugtan** [comment]
I have written the tests for the same as well and they are working fine. Please have a look on the PR when you are free.
screenshot_20190302_151749

**Comment by rtgdk** [comment]
@Ugtan  Nice work!
Although, a separate table with the same schema is never a good idea, remember, DRY (don't repeat yourself). If you have to change the schema for one, you will have to change the schema for the other, this can lead to bugs. Also, while copying the datafields
We can use the archive field to query license request and archived request in the same `LicenseRequest Table`.

**Comment by Ugtan** [comment]
@rtgdk I totally agree with you and will definitely not repeat it. Will update it soon.

**Comment by Ugtan** [comment]
@rtgdk I have updated it please have a look at it. Thanks

**Comment by rtgdk** [comment]
@Ugtan By clicking on archive, it should remove the data row from the list immediately(using javascript). The user should not have to refresh to update the changes.

**Comment by Ugtan** [comment]
@rtgdk Okay i will update it soon.

**Comment by Ugtan** [comment]
@rtgdk I have updated the branch with the requested changes. Please have a look and ping me for any queries.

**Comment by rtgdk** [comment]
@Ugtan Also add a field in `license_information.html` with title "Archived" near the name of the license if it is archived.

**Comment by Ugtan** [comment]
@rtgdk Done. Please have a look.

**Comment by Ugtan** [comment]
@techytushar I agree, there should be a pop up for the archive as well as unarchive license. Will implement that ASAP.

**Comment by Ugtan** [comment]
@rtgdk @techytushar Done. Please have a look. I will also attach the SC of the tests below.
image

**Comment by techytushar** [comment]
Nice work @Ugtan, but instead of the using default browser popups I would recommend to use the bootstrap's popups as used in the other parts of the website, since the default popups may be blocked by the user

**Comment by Ugtan** [comment]
@techytushar @rtgdk Done. Please have a look.

**Comment by Ugtan** [comment]
Thanks 😊 @techytushar

**Comment by rtgdk** [comment]
@Ugtan Great work! Thanks!

**Comment by Ugtan** [comment]
Thank you :) @rtgdk

**Pull request merged**
