### PR TITLE
Change focus on error and scroll to the top when submitting a new license

### LINKED ISSUE #109: Change focus on error when submitting a new license
When a field fails validation, the error is displayed at the top of the page.  If you are scrolled at the bottom, you don't see the error message.

Scrolling to the top of the page where the error is would highlight the error and solve the issue.

It would also help to highlight the field in error in red.

### PR DESCRIPTION
**Pull request by Ugtan**
Fixes #109

### CODE REVIEW

**Comment by rtgdk** [comment]
The scroll up is quite sudden. Can you add animation to that?

**Comment by Ugtan** [comment]
@rtgdk Done. Please have a look to see if its okay now.

**Comment by goneall** [comment]
LGTM - Thanks @Ugtan

@rtgdk  , if it looks good to you, please go ahead and merge.

**Comment by Ugtan** [comment]
Thank you 😊 @goneall @teckytushar

**Pull request merged**
