### PR TITLE
Added drag and drop capabilities to document uploading 

### PR DESCRIPTION
**Pull request by freddy28**
@rtgdk @pombredanne @goneall 
Added drag and drop capabilities to document uploading. 
ISSUE_FIXED: Issue [#7 ](https://github.com/spdx/spdx-online-tools/issues/7)
Please review and let me know about your ideas. 

Thanks

### CODE REVIEW

**Comment by goneall** [comment]
@freddy28 I noticed a few binary files in the commit - are those binaries necessary?  If not, could you remove from the commit?

**Comment by rtgdk** [comment]
@freddy28  You might have noticed that the tool is not functional when we upload the file by drag and drop. You need to integrate the pre-upload feature of dropzone(uploading before submitting the form) with the submit form button so that proper dialog box is opened. Also, when we upload a file through the browse feature, convert and compare feature don't work.
Also, just to make it easy and simple, if we are able to implement the drag-drop feature we wouldn't need two separate form submission on convert page. The validate feature works but we would need to show the result in the dialog box.
I would suggest, you look into how to stop the pre-upload feature and then integrate the file linked by dropzone to the file used by views function. The views function would be called by clicking on the submit button only. It should not be called as soon as the file is uploaded. So change this feature too.
Also, remove unnecessary files before commiting.

**Comment by pombredanne** [comment]
@freddy28  Can you add a DCO signoff to your commit?
See https://developercertificate.org/
And also remove the duplication in your commit message?

**Comment by rtgdk** [comment]
@freddy28  Please remove unnecessary binary files from commit, also update your fork master with the current master branch to resolve the merge conflicts.

**Comment by rtgdk** [comment]
Work completed in #28 . Closing this PR.

**Pull request closed without merging**
