### PR TITLE
Fix malformed xml  which converting bytes to str in py3

### PR DESCRIPTION
**Pull request by rtgdk**
#272

### CODE REVIEW

**Comment by goneall** [comment]
I tried this out on the server that has the bad data and I got the following error:

`AttributeError: 'str' object has no attribute 'decode'`

I look in the database and the data is stored as a quoted string prepended with b (e.g. `b'<xml stuff`).

**Comment by rtgdk** [comment]
Oh 😓 Then I believe we need to look through the codebase for other model fields too since some might be saved as bytes and some as string. To fix this we can add the check to do decode if it is not an instance of string.

**Comment by goneall** [comment]
This is now working on my test machine, but there are two new issues: #275 and #274

**Comment by goneall** [comment]
I just created a PR #276 against this PR branch to resolve the issues mentioned above

**Review by goneall — APPROVED** [review]

**Pull request merged**
