### PR TITLE
Create an issue when license is found to be a near match not PR

### LINKED ISSUE #135: Change from creating a PR to creating an issue when there is a close match in a license submittal
PR #128 implements a feature where if there is a close match, the user can submit a pull request to update the XML to allow for the match.

After trying this out on my local machine, it occurred to me that many users may not have the technical skills or interest in creating the XML with the proper `<optional` or `<alt...` tags.  We could instead create an issue with a title "Update [licenseID] to allow matching to the included text".  The text of the license and/or the diff could added as a comment or as an attachment to the issue.

@jlovejoy @swinslow - let me know what you think.

### PR DESCRIPTION
**Pull request by Ugtan**
Changes took place in the commit are:
(1) Create an issue when the license should match based on user's
response.
(2) Add a post screenshot script to post a SC to github.
(3) URL of the screenshot included in issue body.
Fixes #135

### CODE REVIEW

**Comment by Ugtan** [comment]
@goneall @techytushar @rtgdk I have added the changes to create an issue when user clicks on the "license should match", the diff view which occurs when the license is a near match. Now, a screenshot of the diff view will be included in the body of the issue created. For the screenshot, we could create a github account solely for the purpose of storing the images of the diff view. And add the owner with repository name as well as token in the postscreenshot.js file. It is better to store images in a github account other than using third party applications. Please have a look. Thanks

Here is the eg of the screenshot that will be posted.
img15


P.S I recently changed my OS and I by mistake pushed the branch to spdx repostory instead of my own fork repository. I will take care of this from next time. Sorry about that.

**Comment by goneall** [comment]
@Ugtan Thanks for the PR!  Looks good to me.  I plan on testing out and possibly updating the site over the next week.

@rtgdk @techytushar Unless you see any issues, I'll merge this over the weekend or Monday

**Comment by rtgdk** [comment]
Looks good! Great work @Ugtan

**Comment by Ugtan** [comment]
@goneall Please don't merge this rn. I have to update something which I will do in a couple of days. Thanks

**Comment by goneall** [comment]
> Please don't merge this rn. I have to update something which I will do in a couple of days. 

No problem, just let me know when it's ready to merge

**Comment by Ugtan** [comment]
@goneall Sorry for taking too long to fix a bug(I have been very busy lately) but I have finally solved it and I think the PR is good to go and you can test it on your local machine. Also, I would like to mention that for the purpose of storing screenshots we would have to create a github repo and put the `name with owner` and `github token` in the postscreenshot js file to ensure the working in the production environment.

**Comment by goneall** [comment]
@Ugtan Thanks for the fix!

In about 2 weeks (beginning of October), I will work on this and get it into production.

I may ping you for some additional information in a couple weeks if I run into any challenges deploying to production.

**Comment by Ugtan** [comment]
> In about 2 weeks (beginning of October), I will work on this and get it into production.
> 
> I may ping you for some additional information in a couple weeks if I run into any challenges deploying to production.

@goneall Sure. You can ping me anytime and I will try to reply ASAP. Also, I think it should work on atleast every linux system as I have recently shifted from linux -> Archlinux and I installed redis and everything works like a charm.

**Pull request merged**
