### PR TITLE
Add license request url to the generated issue description

### PR DESCRIPTION
**Pull request by Ugtan**
Add a license request URL field to the description of the issue generated in the license submittal feature. It will help in tracking the license faster.

### CODE REVIEW

**Comment by goneall** [comment]
Is it possible to get the server URL from Django rather than hard coding?

**Comment by Ugtan** [comment]
@goneall @techytushar I have updated the branch to take server URL from Django itself. Please have a look. Thanks

**Comment by goneall** [comment]
LGTM - @techytushar you're more of a Python expert than myself - let me know if this looks good and I'll merge.

**Comment by techytushar** [comment]
Yes @goneall changes looks good to me, nice work @Ugtan :+1:

**Pull request merged**
