### PR TITLE
removed "Email address" field

### PR DESCRIPTION
**Pull request by jewishmoses**
As asked here: https://github.com/spdx/spdx-online-tools/issues/367

### CODE REVIEW

**Review by goneall — CHANGES_REQUESTED** [review]
@jewishmoses thanks for submitting the PR.

In reviewing the changes, it looks like the UI removes the email, but in the file app/views.py, the back-end still implements the userEmail fields as well as the license submittal form.  We would need to clean up the back-end as well as the front-end to complete this issue.

**Comment by rtgdk** [comment]
@jewishmoses Can you please make the corresponding backend changes as well? Make the email as optional field and remove it from forms.

**Comment by jlovejoy** [comment]
as I am trying to update other things, I took at try at the "backend" changes here: #389

**Comment by rtgdk** [comment]
Merged into #389 which has backend changes

**Pull request merged**
