### PR TITLE
Fix SubmitLicenseModelsTests tests in python3 branch

### PR DESCRIPTION
**Pull request by HirumalPriyashan**
Addressed followings,

- Fix https://github.com/spdx/spdx-online-tools/issues/341
- Fix https://github.com/spdx/spdx-online-tools/issues/343
- Fix https://github.com/spdx/spdx-online-tools/issues/344

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - Thanks @HirumalPriyashan

**Comment by HirumalPriyashan** [comment]
Hi @goneall, after this PR got merged I have started on refactoring the `tests.py` in `api` app to reduce the file size.
But following tests are continued fail in main branch. Is this also happening in remote environment as well, or is it something due to wrong config in my environment.

```
FAIL: test_compare_api (api.tests.CompareFileUploadTests)
Access get without login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home//spdx-online-tools/src/api/tests.py", line 249, in test_compare_api
    self.assertEqual(resp3.status_code,200)
AssertionError: 400 != 200

======================================================================
FAIL: test_validate_api (api.tests.ValidateFileUploadTests)
Access get without login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home//spdx-online-tools/src/api/tests.py", line 85, in test_validate_api
    self.assertEqual(resp4.status_code,200)
AssertionError: 400 != 200
```

Also there was a need to remove import and usage of `CheckLicenseFileUpload` since that available in the `models` anymore which was producing errors in imports.
https://github.com/spdx/spdx-online-tools/blob/400bbff988b5cb0abc9e3d7813229850b3ff9fd4/src/api/tests.py#L35

I can send the current progress of test refactoring as a draft PR if it is easier for review.

**Comment by goneall** [comment]
@HirumalPriyashan I'm not completely sure on the unit test failures.  I recall seeing similar failures in the past, but it was a while ago and I don't recall the details.

@rtgdk - Can you take a look and provide some feedback?

**Comment by rtgdk** [comment]
`test_compare_api` tests the post api - `api/compare` after logging in with the default users used in `setUp` of `CompareFileUploadTests`. Check whether your username/password is not changed and should work without issue.

Next the api calls the post method on `/api/compare`, check `def compare` in `api/views.py` and where exactly it failing. The post request on views. py doesn't seem to check for user login but it interacts with different models and then set the return status.

**Comment by HirumalPriyashan** [comment]
@rtgdk Thanks for the explanation, I will look into that.

**Pull request merged**
