### PR TITLE
Add tests for split view of License XML Editor

### PR DESCRIPTION
**Pull request by Ugtan**

### CODE REVIEW

**Comment by techytushar** [comment]
Update your local branch with the origin master then work on it, there have been some changes in the `XMLEditorTestCase` and the one you have commited does not contain those changes

**Comment by Ugtan** [comment]
If the `License XML Editor` pull merge first and i force push this branch will that not fix it? @techytushar

**Comment by techytushar** [comment]
There were some changes made to the `XMLEditorTestCases` in #78 PR I was referring to them, it would be better if this branch also contains those changes as it makes it easier for us to review. A good approach for doing this would be to pull the commits to `origin master`, rebase this branch with master and force push the changes.

**Comment by Ugtan** [comment]
Okay, i will update the branch. Thanks for your help :) @techytushar

**Comment by rtgdk** [comment]
LGTM. Nice work!

**Comment by Ugtan** [comment]
Thank you :) @techytushar @rtgdk

**Comment by rtgdk** [comment]
@Ugtan  can you post a successful test run screenshot? Also, I have increased the verbosity of travis test in the master. Can you please update this branch with master and commit, so that the travis run again.

**Comment by Ugtan** [comment]
@rtgdk I have updated the branch with master and the tests are running well. here's the screenshot

image

**Comment by rtgdk** [comment]
@Ugtan  Thanks, I'll merge this.

**Pull request merged**
